{
 "title": "mydashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "All Telemetry Data",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value AS metric,\n  *\nFROM telemetry\nWHERE\n  $__timeFilter(\"timestamp\")\nORDER BY 1,2"
    }
   ]
  },
  { "title": "PA01", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "PA01 Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value AS metric,\n  *\nFROM telemetry\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensorid = 'ns=2;i=23'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "PA01 Humidity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value AS metric,\n  *\nFROM telemetry\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensorid = 'ns=2;i=22'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "PA01 Counter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  \"timestamp\" AS \"time\",\n  value AS metric,\n  *\nFROM telemetry\nWHERE\n  $__timeFilter(\"timestamp\") AND\n  sensorid = 'ns=2;i=24'\nORDER BY 1,2"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_cpu{mode=\"user\"}",
     "legendFormat": "{{ cpu }}"
    }
   ]
  }
 ]
}