version: "3.7"
services:
  demo-logger:
    image: alpine
    networks:
      - idam-test-network
    entrypoint: |
      sh -c 'sh -s << EOF
      while true
        do
          echo "The date is: $$(date +%s)"
          sleep 5
        done
      EOF'
    logging:
      driver: fluentd
      options:
        tag: docker.efk.demo-logger
        fluentd-async-connect: "true"

networks:
  idam-test-network:
    external: true
