version: "3.7"
x-logging: &default-logging
  options:
    max-size: "50m"

services:
  idam-prefect-agent:
    image: registry.gitlab.com/conceptreply/fundings/bmbf/idam-automation-processor/idam-prefect-agent:latest
    network_mode: host
